name: Deploy to AWS EC2 with Docker Compose

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        path: .  # ワークスペースのルートにチェックアウト
        fetch-depth: 0  # リポジトリ全体を取得

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1

    - name: Setup SSH key
      run: |
        mkdir -p /home/runner/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > /home/runner/.ssh/aws_key.pem
        chmod 600 /home/runner/.ssh/aws_key.pem

    
    - name: List workspace structure
      run: |
        pwd
        ls -R


    - name: Create missing directories on EC2
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
      run: |
        ssh -i /home/runner/.ssh/aws_key.pem -o StrictHostKeyChecking=no ${EC2_USER}@${EC2_HOST} << 'EOF'
          mkdir -p /home/ec2-user/zubolaapp/storage/framework/testing
          mkdir -p /home/ec2-user/zubolaapp/storage/framework/views
          mkdir -p /home/ec2-user/zubolaapp/storage/logs
        EOF
    
    - name: Copy application files to EC2 (excluding tests)
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
      run: |
        echo "Copying zubolaapp to EC2 (excluding test folder)..."
        rsync -avz --no-perms --omit-dir-times --delete \
          --exclude '/tests' \
          -e "ssh -i /home/runner/.ssh/aws_key.pem -o StrictHostKeyChecking=no" \
          ./zubolaapp/ ${EC2_USER}@${EC2_HOST}:/home/ec2-user/zubolaapp || { echo "rsync error occurred"; exit 1; }
    
    - name: Copy test folder to EC2
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
      run: |
        echo "Copying test folder to EC2..."
        rsync -avz --no-perms --omit-dir-times --delete \
          -e "ssh -i /home/runner/.ssh/aws_key.pem -o StrictHostKeyChecking=no" \
          ./zubolaapp/tests ${EC2_USER}@${EC2_HOST}:/home/ec2-user/zubolaapp/tests || { echo "rsync error occurred for tests folder"; exit 1; }



    - name: Verify docker-compose.yml on EC2
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
      run: |
        ssh -i /home/runner/.ssh/aws_key.pem -o StrictHostKeyChecking=no ${EC2_USER}@${EC2_HOST} << 'EOF'
          # 確認: docker-compose.ymlが存在するか
          if [ ! -f /home/ec2-user/zubolaapp/docker-compose.yml ]; then
            echo "Error: docker-compose.yml not found in /home/ec2-user/zubolaapp"
            exit 1
          else
            echo "docker-compose.yml found. Proceeding with deployment..."
          fi
        EOF
    
    - name: SSH into EC2 and deploy with Docker Compose
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
      run: |
        ssh -i /home/runner/.ssh/aws_key.pem -o StrictHostKeyChecking=no ${EC2_USER}@${EC2_HOST} << 'EOF'
          cd /home/ec2-user/zubolaapp
          docker-compose down  # 一旦停止
          docker-compose up -d --build  # 最新の状態でビルドと起動
        EOF
