name: Deploy to AWS EC2 with Docker Compose

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1

    - name: Copy files to EC2
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
      run: |
        echo "Setting up SSH key..."
        mkdir -p /home/runner/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > /home/runner/.ssh/aws_key.pem
        chmod 600 /home/runner/.ssh/aws_key.pem
        echo "Copying files to EC2 using rsync..."
        if [ -d "${GITHUB_WORKSPACE}/tests" ]; then
          rsync -avz --no-perms --omit-dir-times --delete \
            -e "ssh -i /home/runner/.ssh/aws_key.pem -o StrictHostKeyChecking=no" \
            "${GITHUB_WORKSPACE}/tests" ${EC2_USER}@${EC2_HOST}:/home/ec2-user/zubolaapp/tests
        else
          echo "The tests directory does not exist."
          exit 1
        fi
        
    - name: List project files
      run: |
        pwd
        ls -R "${GITHUB_WORKSPACE}"


    - name: SSH into EC2 and deploy with Docker Compose
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
      run: |
        ssh -i ~/.ssh/aws_key.pem -o StrictHostKeyChecking=no ${EC2_USER}@${EC2_HOST} << 'EOF'
          cd /home/ec2-user/zubolaapp
          docker-compose down
          docker-compose up -d --build
        EOF

